WebApp/Areas/ApiDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Areas.ApiDemo
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApp/Controllers/CertificatesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.DAL.Data;
using WebApp.DAL.Entities;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CertificatesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public CertificatesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Certificates
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Certificate>>> GetCertificates(int? group)
        {
            return await _context.Certificates.Where(d => !group.HasValue || d.CertificateGroupId.Equals(group.Value))?.ToListAsync();
        }

        // GET: api/Certificates/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Certificate>> GetCertificate(int id)
        {
            var certificate = await _context.Certificates.FindAsync(id);

            if (certificate == null)
            {
                return NotFound();
            }

            return certificate;
        }

        // PUT: api/Certificates/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutCertificate(int id, Certificate certificate)
        {
            if (id != certificate.CertificateId)
            {
                return BadRequest();
            }

            _context.Entry(certificate).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CertificateExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Certificates
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Certificate>> PostCertificate(Certificate certificate)
        {
            _context.Certificates.Add(certificate);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetCertificate", new { id = certificate.CertificateId }, certificate);
        }

        // DELETE: api/Certificates/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Certificate>> DeleteCertificate(int id)
        {
            var certificate = await _context.Certificates.FindAsync(id);
            if (certificate == null)
            {
                return NotFound();
            }

            _context.Certificates.Remove(certificate);
            await _context.SaveChangesAsync();

            return certificate;
        }

        private bool CertificateExists(int id)
        {
            return _context.Certificates.Any(e => e.CertificateId == id);
        }
    }
}

WebApp/Areas/ApiDemo/Pages/Index.cshtml
@page
@model WebApp.Areas.ApiDemo.IndexModel

@{
    ViewData["Title"] = "Index";
}

<table class="table table-striped table-sm" id="list">
</table>
<div class="lead" id="info"></div>

@section Scripts
{
    <script>
        var url = "@Url.Action("GetCertificates", "Certificates")";
        $(document).ready(function () {
            // послать запрос
            $.getJSON(url, function (data) {
                // найти таблицу по id
                var table = $("#list");
                // сформировать строку для каждого полученного объекта
                $.each(data, function (num, value) {
                    createRow(num + 1, value).appendTo(table);
                })
            });
        })

        // Функция формирования одной строки таблицы
        // index - порядковый номер
        // data - объект данных
        function createRow(index, data) {
            // создать строку таблицы
            var row = $("<tr>");
            // добавть колонку с порядковым номером
            row.append("<td>" + index + "</td>");
            // добавить колонку с названием
            row.append("<td>" + data.certificateName + "</td>");
            // создать кнопку
            var button = $("<button>")
                .addClass("btn btn-success")
                .click(data.certificateId, showDetails)
                .text("Подробно");
            // создать колонку с кнопкой
            var td = $("<td>").append(button);
            // добавить в строку таблицы
            row.append(td);
            return row;
        }

        //Функция выода информации о выбранном объекте
        function showDetails(e) {
            // Послать запрос
            $.getJSON(url + "/" + e.data, function (data) {
                // строка информации об объекте
                var details = data.certificateName + ": "
                    + data.description + " - "
                    + data.price + " BYN";
                $("#info").empty().text(details);
            })
        }
    </script>
}