WebApp/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApp.Models;

namespace WebApp.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> _menuItems = new List<MenuItem> {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
            new MenuItem{ Controller="Product", Action="Index",Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index",Text="Администрирование"},
            new MenuItem{ IsPage=true, Area="ApiDemo", Page="/Index",Text="API-demo"}
        };

        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;
                // Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

WebApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.DAL.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(_cart.Items.Values);
        }

        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            var item = _context.Certificates.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }     
    }
}

WebApp/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">903217</a>
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index">Lab 2</a>
                    <a class="nav-item nav-link" asp-controller="Product" asp-action="Index">Каталог</a>
                    <a class="nav-item nav-link" asp-area="Admin" asp-page="/Index">Администрирование</a>
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <a asp-controller="Cart" asp-action="Index" class="navbar-text ml-auto">
                    00,0 руб
                    <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown"
                         aria-haspopup="true" aria-expanded="false">
                        <img src="~/images/avatar.png" width="30" alt="User" class="rounded" />
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="~/images/avatar.png" width="50" alt="User" class="rounded" /> user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Cart" asp-action="Index">Мои товары</a>
                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">Log off</a>
                    </div>
                </div>
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->

        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">
        @RenderBody()
    </main>
    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">903217</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container" style="margin-bottom:60px">
        @RenderBody()
    </main>
    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_UserPartial.cshtml
<!-- Информация пользователя -->
@using Microsoft.AspNetCore.Identity;
@using WebApp.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="50" alt="User"
                     class="rounded bg-light" />
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Cart" asp-action="Index">Мои товары</a>
            <form asp-area="Identity"
                  asp-page="/Account/Logout"
                  asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit"
                       value="Log off"
                       class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}
<!-- Информация пользователя - конец -->